### ISSUE TITLE
Month off by +1 when converting to Ethiopic date 

### ISSUE THREAD

**Issue by m3hari** [Miqe/ken.js#12]
Today is 
2017-04-30 g.c
2009-08-22 e.c
_____________________________________________
When converting to Ethiopic calendar, the month is off by +1. Here is a snippet to reproduce the issue.

```
var today  = new Ken(new Date());
today.toEC().toString();
```
returns  "2009-09-22"

**Comment by miqe** [comment]
Thanks, that only happened when using Date Object as ken input.
Fixed with #13
