### ISSUE TITLE
Testing kenjs

### ISSUE THREAD

**Issue by m3hari** [Miqe/ken.js#17]
What is the plan regarding testing kenjs. Here is a test from another repository that implements Ethiopian calendar with java. I think the test suites would help here.

https://github.com/geezorg/geezorg.github.io/blob/master/Calendars/EthiopicCalendarTest.java

**Comment by miqe** [comment]
How do i check if this conversion from your test are correct?
  * Ethiopic      Gregorian     JDN
    * 20/02/1855    29/10/1862    2401443
    * 29/10/1857    05/07/1865    2402423
    * 22/05/1858    29/01/1866    2402631
    * 10/08/1858    17/04/1866    2402709
    * 28/04/1859    05/01/1867    2402972
    * 05/05/1860    13/01/1868    2403345

**Comment by miqe** [comment]
here is my proposal?
lets test some recent date on ken.js on the one section and if the test pass those days then lets test 100 or 200 years back untill the test passes (20/02/1855 EC=> 29/10/1862 GC)  on another section. then we can agree if the second section test goes incrementally without jumping any date and passes all test then **the test would be precise**  and the predefined test use case would be **incorrect**.

**Comment by m3hari** [comment]
All look fine we can close this for now.
