### ISSUE TITLE
some Gregorian dates are not converted properly 

### ISSUE THREAD

**Issue by b3rew** [Miqe/ken.js#3]
for example if we convert "2017-09-10" to Ethiopian Date 

```
Ken().toEth(new Date("2017-09-10")) // we will get 5-13-2009 
```
which is correct but the next date which is "2017-09-11"

```
Ken().toEth(new Date("2017-09-11")) // returns "36-1-2009"
```

the month is correct but the date & year are not

thanks

**Comment by miqe** [comment]
Fixed with  #5
