### ISSUE TITLE
Incorrect Conversion

### ISSUE THREAD

**Issue by utopiaio** [Miqe/ken.js#6]
The conversion algorithm is not correct (attached an image for example). For conversion, one should / **must** use [Beyene-Kudlek algorithm](http://www.geez.org/Calendars/). There are implementations for it (with tests) [Java](https://github.com/geezorg/geezorg.github.io/blob/master/Calendars/EthiopicCalendar.java), [JavaScript](https://github.com/moe-szyslak/Ethiopic-Calendar), _Swift coming soon_

Also, was there a reason to mutate `Date` object? As the `Date` object itself is not consistent across browsers it might cause edge case problems

When putting out Number / Date conversion for Ethiopic, one should be **careful** as most people will take it as-is

PS / Self Promotion
Both [Ethiopic-Calendar](https://github.com/moe-szyslak/Ethiopic-Calendar) and [Geezer](https://github.com/moe-szyslak/Geezer) were used in [Showtime](https://vimeo.com/194029357). I decided to give them their own repositories a while back as I thought people might find them useful

PPS
Head on to [geez.org](http://www.geez.org). It is an absolute joy to read

![wrong conversion](https://i.imgur.com/J5xbHy8.png)

**Comment by miqe** [comment]
I know  Beyene-Kudlek algorithm works well but i am trying to develop my own algorithm. 
As you suggested I've dropped the date mutation section, it was added for ease of access. 
Thanks for the heads up, i'll add tests and continuous integration soon.
if i had known  Ethiopic-Calendar was there before i started working on ken.js i would have definitely used that. 
Fixed this issue with #9 merge.
![screenshot from 2017-04-19 14-18-09](https://cloud.githubusercontent.com/assets/10463154/25177672/7d542c48-250b-11e7-9152-9c2d4c3e6404.png)

**Comment by utopiaio** [comment]
> I know Beyene-Kudlek algorithm works well but I am trying to develop my own algorithm

That's a pretty bold move imo. The conversion algorithm has already been done. It would be better to implement it different languages rather than _reinventing_ the wheel but then again having a **better** algorithm is always a 👍

I'll be watching this repository to see where the new algorithm lands 🥇
